apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rorai-tenant/my-app-1/devfile-sample@sha256:c44ff528f0b2003e8c1ae0ff595d0d113126927307fa74969a6f2a638f91b2b8
        name: my-nodejs
        resources: {}
status: {}
